import fs from "fs";
import path from "path";
import type { Edl, SubtitleStyle, WordEntry } from "../types";
import { loadWords } from "./project";

/**
 * Build a standalone .ass subtitle file from per-source transcripts + EDL
 * output-timeline offsets (Hard Rule 5: output_time = word.start - seg.start + seg.offset).
 *
 * A full .ass with the style baked into [V4+ Styles] is used instead of
 * force_style — Session 3 found force_style silently fails on some libass builds.
 *
 * Chunking modes:
 *  - "two-word": 2-word UPPERCASE chunks, break on punctuation (the shipped bold-overlay style)
 *  - "natural": a handful of words per cue; hard-break on gaps ≥ 0.9s always,
 *    soft-break on gaps ≥ 0.45s only once the chunk has ≥ 3 words, cap at 6 words.
 */

interface Cue {
  start: number;
  end: number;
  text: string;
}

const PUNCT = new Set([".", ",", "!", "?", ";", ":"]);

function chunkWords(words: WordEntry[], mode: SubtitleStyle["chunkMode"]): WordEntry[][] {
  const chunks: WordEntry[][] = [];
  let cur: WordEntry[] = [];
  for (let i = 0; i < words.length; i++) {
    const w = words[i];
    if (!w.t) continue;
    cur.push(w);
    const gap = i + 1 < words.length ? words[i + 1].s - w.e : Infinity;
    const endsPunct = PUNCT.has(w.t[w.t.length - 1]);
    let breakHere = false;
    if (mode === "two-word") {
      breakHere = cur.length >= 2 || endsPunct;
    } else {
      if (gap >= 0.9) breakHere = true;
      else if (gap >= 0.45 && cur.length >= 3) breakHere = true;
      else if (cur.length >= 6) breakHere = true;
      else if (endsPunct && cur.length >= 3) breakHere = true;
    }
    if (breakHere) {
      chunks.push(cur);
      cur = [];
    }
  }
  if (cur.length) chunks.push(cur);
  return chunks;
}

export function buildCues(dir: string, edl: Edl, style: SubtitleStyle): Cue[] {
  const cues: Cue[] = [];
  let offset = 0;
  const wordCache = new Map<string, WordEntry[]>();

  for (const r of edl.ranges) {
    const segDur = r.end - r.start;
    let words = wordCache.get(r.source);
    if (words === undefined) {
      try {
        words = loadWords(dir, r.source);
      } catch {
        words = [];
      }
      wordCache.set(r.source, words);
    }
    const inSeg = words.filter((w) => w.e > r.start && w.s < r.end);
    for (const chunk of chunkWords(inSeg, style.chunkMode)) {
      const s = Math.max(r.start, chunk[0].s);
      const e = Math.min(r.end, chunk[chunk.length - 1].e);
      let text = chunk.map((w) => w.t).join(" ").replace(/\s+/g, " ").trim();
      text = text.replace(/[,;:]+$/, "");
      if (style.uppercase) text = text.toUpperCase();
      const outS = Math.max(0, s - r.start) + offset;
      let outE = Math.max(0, e - r.start) + offset;
      if (outE <= outS) outE = outS + 0.4;
      cues.push({ start: outS, end: Math.min(outE, offset + segDur), text });
    }
    offset += segDur;
  }
  cues.sort((a, b) => a.start - b.start);
  return cues;
}

function assTime(t: number): string {
  const cs = Math.round(t * 100);
  const h = Math.floor(cs / 360000);
  const m = Math.floor((cs % 360000) / 6000);
  const s = Math.floor((cs % 6000) / 100);
  const c = cs % 100;
  return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}.${String(c).padStart(2, "0")}`;
}

function assColor(hex: string, alpha = 0): string {
  const h = hex.replace("#", "");
  const r = h.slice(0, 2);
  const gg = h.slice(2, 4);
  const b = h.slice(4, 6);
  const a = Math.round(alpha * 255).toString(16).padStart(2, "0");
  return `&H${a}${b}${gg}${r}`.toUpperCase();
}

export function buildAss(opts: {
  dir: string;
  edl: Edl;
  style: SubtitleStyle;
  frameW: number;
  frameH: number;
}): string {
  const { dir, edl, style, frameW, frameH } = opts;
  const cues = buildCues(dir, edl, style);

  const playResX = frameW;
  const playResY = frameH;
  const fontSize = Math.round((style.sizePct / 100) * playResY);
  const marginV = Math.round((style.marginVPct / 100) * playResY);
  const marginLR = Math.round(((100 - style.maxWidthPct) / 200) * playResX);
  const isBox = style.backdrop === "box";
  const backAlpha = isBox ? 1 - style.boxOpacity : 0;

  const header = `[Script Info]
; Generated by video-use studio — style baked into V4+ Styles (not force_style)
ScriptType: v4.00+
PlayResX: ${playResX}
PlayResY: ${playResY}
ScaledBorderAndShadow: yes
WrapStyle: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Studio,${style.fontFamily},${fontSize},${assColor(style.primaryColor)},${assColor(style.primaryColor)},${assColor(style.outlineColor)},${assColor("#000000", backAlpha)},${style.bold ? -1 : 0},0,0,0,100,100,0,0,${isBox ? 3 : 1},${isBox ? Math.max(4, Math.round(fontSize * 0.18)) : Math.max(2, Math.round(fontSize * 0.08))},0,2,${marginLR},${marginLR},${marginV},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

  const events = cues
    .map(
      (c) =>
        `Dialogue: 0,${assTime(c.start)},${assTime(c.end)},Studio,,0,0,0,,${c.text.replace(/\n/g, "\\N")}`
    )
    .join("\n");

  return header + events + "\n";
}

export function writeSubtitles(opts: {
  dir: string;
  edl: Edl;
  style: SubtitleStyle;
  frameW: number;
  frameH: number;
}): { assPath: string; cueCount: number } {
  const ass = buildAss(opts);
  const ed = path.join(opts.dir, "edit");
  fs.mkdirSync(ed, { recursive: true });
  const assPath = path.join(ed, "master.ass");
  // Don't clobber a hand-built master.ass that the studio didn't create.
  if (fs.existsSync(assPath) && !fs.existsSync(path.join(ed, "studio_subs.json"))) {
    const ts = new Date().toISOString().replace(/[:.]/g, "-");
    fs.copyFileSync(assPath, path.join(ed, `master.ass.bak-${ts}`));
  }
  fs.writeFileSync(assPath, ass);
  fs.writeFileSync(path.join(ed, "studio_subs.json"), JSON.stringify(opts.style, null, 2));
  const cueCount = (ass.match(/^Dialogue:/gm) ?? []).length;
  return { assPath, cueCount };
}
